export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FAIL = "GET_DATA_FAIL"
export const SORT_DATA = "SORT_DATA"
export const UPDATE_DATA = "UPDATE_DATA"
export const FILTER_DATA = "FILTER_DATA"
export const FILTERS_SET = "FILTERS_SET"
export const FILTERS_RESET = "FILTERS_RESET"